compress_html:
  clippings: all
  comments: all
  endings: all
  startings: [html, head, body]
sass:
  style: compressed
include:
  - _headers
exclude:
  - README.md
  - LICENSE
  - Gemfile*
