site_title: "AS200078 | Potat0 Network"
title: "Potat0 Network"
subtitle: "A Research&#8209;Based Network Operated By&nbspPotat0"
SSOdescription: "Potat0 Network, A Research-Based Network"
SSOkeywords: "AS200078 Potat0 Network"
icon:
  ethernet: "M0 224V416c0 17.7 14.3 32 32 32H96V336c0-8.8 7.2-16 16-16s16 7.2 16 16V448h64V336c0-8.8 7.2-16 16-16s16 7.2 16 16V448h64V336c0-8.8 7.2-16 16-16s16 7.2 16 16V448h64V336c0-8.8 7.2-16 16-16s16 7.2 16 16V448h64c17.7 0 32-14.3 32-32V224c0-17.7-14.3-32-32-32H448V160c0-17.7-14.3-32-32-32H384V96c0-17.7-14.3-32-32-32H160c-17.7 0-32 14.3-32 32v32H96c-17.7 0-32 14.3-32 32v32H32c-17.7 0-32 14.3-32 32z"
  envelope: "M48 64C21.5 64 0 85.5 0 112c0 15.1 7.1 29.3 19.2 38.4L236.8 313.6c11.4 8.5 27 8.5 38.4 0L492.8 150.4c12.1-9.1 19.2-23.3 19.2-38.4c0-26.5-21.5-48-48-48H48zM0 176V384c0 35.3 28.7 64 64 64H448c35.3 0 64-28.7 64-64V176L294.4 339.2c-22.8 17.1-54 17.1-76.8 0L0 176z"
info:
  - icon: ethernet
    text: AS200078
  - icon: envelope
    text: noc@potat0.cc
    # url: "mailto:noc@potat0.cc"
  - icon: envelope
    text: abuse@potat0.cc
    # url: "mailto:abuse@potat0.cc"
link:
  - text: PeeringDB
    url: https://www.peeringdb.com/asn/200078
  - text: bgp.tools
    url: https://bgp.tools/as/200078
  - text: HE
    url: https://bgp.he.net/AS200078
section:
  - title: Introduce
    content: |
      Potat0 Network (AS200078) is an education & research network operated by Potat0. This network only supports IPv6.

  - title: Peering
    content: |
      I have an open peering policy.

      I peer with route servers at Internet eXchange Points and send identical routes with general peerings. Besides, setting up a private peering session with me through Internet eXchanges that we have in common, or establishing the session via a tunnel (WireGuard, GRE, etc.), is always welcome.

      For your convenience, here is some information about peering.

      - ASN: `200078`
      - AS-SET: `AS200078:AS-SET`
      - Suggested prefix limit for IPv4: `0`
      - Suggested prefix limit for IPv6: `30`

  - title: IX
    content: |
      - [ZXIX Hangzhou](https://www.peeringdb.com/ix/3166)

      - [ZXIX Hong Kong](https://www.peeringdb.com/ix/3246)

      - [MoeIX SEA](https://www.peeringdb.com/ix/4082)

  - title: PoP
    content: |
      - `CN1`<br>
        Hangzhou, Zhejiang Province, China

      - `CN2`<br>
        Shenyang, Liaoning Province, China

      - `US1`<br>
        Las Vegas, Nevada, USA

      - `JP1`<br>
        Tokyo, Japan

      - `NO1`<br>
        Sandefjord, Vestfold og Telemark, Norway

      - `US2`<br>
        Seattle, Washington, USA

      - `DE1`<br>
        Falkenstein, Saxony-Anhalt, Germany

      - `CN3`<br>
        Zhengzhou, Henan Province, China

      - `CN4`<br>
        Xi'an, Shaanxi Province, China
    map:
      - latitude: 30.25
        longitude: 120.1675
        content: |
          `CN1`

          Hangzhou, Zhejiang Province, China

          ZXIX Hangzhou
      - latitude: 41.8039
        longitude: 123.4258
        content: |
          `CN2`

          Shenyang, Liaoning Province, China
      - latitude: 36.2333
        longitude: -115.2654
        content: |
          `US1`

          Las Vegas, Nevada, USA

          BuyVM
      - latitude: 35.6897
        longitude: 139.6922
        content: |
          `JP1`

          Tokyo, Japan

          AWS Lightsail
      - latitude: 59.1288
        longitude: 10.2197
        content: |
          `NO1`

          Sandefjord, Vestfold og Telemark, Norway

          Terrahost
      - latitude: 47.6211
        longitude: -122.3244
        content: |
          `US2`

          Seattle, Washington, USA

          MoeIX SEA
      - latitude: 51.7333
        longitude: 11.3333
        content: |
          `DE1`

          Falkenstein, Saxony-Anhalt, Germany
      - latitude: 34.7492
        longitude: 113.6605
        content: |
          `CN3`

          Zhengzhou, Henan Province, China
      - latitude: 34.2667
        longitude: 108.9
        content: |
          `CN4`

          Xi'an, Shaanxi Province, China
  - title: Upstreams
    content: |
      - BuyVM (AS53667)

      - Terrahost (AS56655)

      - MoeQing Network (AS138211)
