site_title: "AS200078 | Potat0 Network"
title: "Potat0 Network"
subtitle: "A Research&#8209;Based Network Operated By&nbspPotat0"
SSOdescription: "Potat0 Network, A Research-Based Network"
SSOkeywords: "AS200078 Potat0 Network"
CloudflareToken: "36f48af0ff314d039568586b37456c71"
GoogleGTagID: "G-QL9GFW9M3W"
icon:
  ethernet: "M0 224V416c0 17.7 14.3 32 32 32H96V336c0-8.8 7.2-16 16-16s16 7.2 16 16V448h64V336c0-8.8 7.2-16 16-16s16 7.2 16 16V448h64V336c0-8.8 7.2-16 16-16s16 7.2 16 16V448h64V336c0-8.8 7.2-16 16-16s16 7.2 16 16V448h64c17.7 0 32-14.3 32-32V224c0-17.7-14.3-32-32-32H448V160c0-17.7-14.3-32-32-32H384V96c0-17.7-14.3-32-32-32H160c-17.7 0-32 14.3-32 32v32H96c-17.7 0-32 14.3-32 32v32H32c-17.7 0-32 14.3-32 32z"
  envelope: "M48 64C21.5 64 0 85.5 0 112c0 15.1 7.1 29.3 19.2 38.4L236.8 313.6c11.4 8.5 27 8.5 38.4 0L492.8 150.4c12.1-9.1 19.2-23.3 19.2-38.4c0-26.5-21.5-48-48-48H48zM0 176V384c0 35.3 28.7 64 64 64H448c35.3 0 64-28.7 64-64V176L294.4 339.2c-22.8 17.1-54 17.1-76.8 0L0 176z"
info:
  - icon: ethernet
    text: AS200078
  - icon: envelope
    text: noc@potat0.cc
    # url: "mailto:noc@potat0.cc"
  - icon: envelope
    text: abuse@potat0.cc
    # url: "mailto:abuse@potat0.cc"
link:
  - text: PeeringDB
    url: https://www.peeringdb.com/asn/200078
  - text: bgp.tools
    url: https://bgp.tools/as/200078
  - text: HE
    url: https://bgp.he.net/AS200078
section:
  - title: Introduce
    markdown: |
      Potat0 Network (AS200078) is an education & research network operated by Potat0. This network only supports IPv6.

  - title: Peering
    markdown: |
      I have an open peering policy.

      I peer with route servers at Internet eXchange Points and send identical routes with general peerings. Besides, setting up a private peering session with me through Internet eXchanges that we have in common, or establishing the session via a tunnel (WireGuard, GRE, etc.), is always welcome.

      For your convenience, here is some information about peering.

      - ASN: `200078`
      - AS-SET: `AS200078:AS-SET`
      - Suggested prefix limit for IPv4: `0`
      - Suggested prefix limit for IPv6: `30`

      If you implemented some kind of whitelisting mechanism, here's a list of the prefixes I have

      - `2a0e:aa07:e050::/44`
      - `2a13:b487:1100::/40`
      - `2a13:a5c3:f200::/40`
      - `2406:840:9980::/44`

  - title: IX
    ix:
      - name: LOCIX FRANKFURT
        peeringdb: 2084
      - name: BGP.Exchange Kansas City
        peeringdb: 3835
      - name: BGP.Exchange Hong Kong
        peeringdb: 3825
      - name: BGP.Exchange Frankfurt
        peeringdb: 3829
      - name: BGP.Exchange Fremont
        peeringdb: 3828
      - name: HN Internet Exchange
        peeringdb: 4379
      - name: Zero Internet eXchange San Jose
        peeringdb: 4242
      - name: ZXIX Hangzhou
        peeringdb: 3166
      - name: ZXIX Hong Kong
        peeringdb: 3246
      - name: 4b42 Internet Exchange Point
        peeringdb: 2447

  - title: PoP
    markdown: |
      - `LAS`<br>
        Las Vegas, Nevada, USA

      - `HKG`<br>
        Hong Kong SAR, China

      - `FRA`<br>
        Frankfurt, Germany

      - `SJC`<br>
        San Jose, California, USA

  - title: Upstreams
    upstreams:
      - name: FranTech Solutions | BuyVM
        asn: 53667
      - name: Skywolf Technology LLC
        asn: 7720
      - name: xTom OU
        asn: 3204
      - name: MoeDove LLC
        asn: 44324
      - name: Hurricane Electric LLC
        asn: 6939
      - name: Hyper Group Network Ltd
        asn: 216324
