name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true
      - name: Setup Python
        uses: actions/setup-python@main
        with:
          python-version: 3.x
      - name: Build
        run: |
          bundle exec jekyll build
          sed -i -E 's/favicon\.[0-9a-f]{8}\.svg/favicon.svg/g' _site/index.html
      - name: Minify
        uses: docker://devatherock/minify-js:3.0.0
        with:
          directory: _site
          add_suffix: false
          inclusions: index.html
      - name: Deploy to TencentCloud COS
        env:
          SECRET_ID: ${{ secrets.TENCENTCLOUD_SECRET_ID }}
          SECRET_KEY: ${{ secrets.TENCENTCLOUD_SECRET_KEY }}
          REGION: ap-guangzhou
          BUCKET: as200078-info-1307988268
        run: |
          pip install coscmd
          coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
          cd _site
          coscmd upload -rfs --delete ./ /
      - name: Refresh and Prefetch TencentCloud EdgeOne
        env:
          TENCENTCLOUD_SECRET_ID: ${{ secrets.TENCENTCLOUD_SECRET_ID }}
          TENCENTCLOUD_SECRET_KEY: ${{ secrets.TENCENTCLOUD_SECRET_KEY }}
          TENCENTCLOUD_REGION: ap-guangzhou
        run: |
          pip install tccli
          tccli teo CreatePurgeTask --cli-unfold-argument --ZoneId zone-3d2iwq53tqx6 --Type purge_host --Targets 'net.potat0.cc'
          tccli teo CreatePrefetchTask --cli-unfold-argument --ZoneId zone-3d2iwq53tqx6 --Targets 'https://net.potat0.cc/index.html' 'https://net.potat0.cc/geofeed.csv' 'https://net.potat0.cc/favicon.svg' 'https://net.potat0.cc/robots.txt' 'https://net.potat0.cc/sitemap.xml'
