name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true
      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: lts/*
      - name: Build
        run: bundle exec jekyll build
      - name: Rename favicon
        run: |
          cd _site
          hash=$(sha1sum favicon.svg)
          mv favicon.svg favicon.${hash: :8}.svg
      - name: Minify
        uses: docker://devatherock/minify-js:3.0.0
        with:
          directory: _site
          add_suffix: false
          inclusions: index.html
      - name: Deploy to EdgeOne Pages
        run: npx edgeone pages deploy ./_site -n as200078-info -t ${{secrets.EDGEONE_API_TOKEN}}
